
import javax.swing.JOptionPane;
/**
 * GUI.java
 * 10/03/2026
 * @author DENISE BALASMEH
 * x24701351
 */

public class GUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI.class.getName());
    
    ParkingStack parkingStack = new ParkingStack();
    ParkingList waitingList = new ParkingList();

    private final int maxSpaces = 5;
    private int parkedBikes = 0;

    /**
     * Creates new form GUI
     */
    public GUI() {
        getContentPane().setBackground(new java.awt.Color(199, 233, 237)); //CHANGE GUI COLOUR
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bikeIdLbl = new javax.swing.JLabel();
        ownerNameLbl = new javax.swing.JLabel();
        bikeIdTF = new javax.swing.JTextField();
        OwnerNameTF = new javax.swing.JTextField();
        CheckAvailSpaceBtn = new javax.swing.JButton();
        ParkBikeBtn = new javax.swing.JButton();
        JoinWaitingListBtn = new javax.swing.JButton();
        RemoveBikeBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("DOCKLAND BPM");

        bikeIdLbl.setText("Bike id:");

        ownerNameLbl.setText("Owner name:");

        bikeIdTF.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        bikeIdTF.setForeground(new java.awt.Color(255, 255, 255));
        bikeIdTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bikeIdTFActionPerformed(evt);
            }
        });

        OwnerNameTF.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        OwnerNameTF.setForeground(new java.awt.Color(255, 255, 255));
        OwnerNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OwnerNameTFActionPerformed(evt);
            }
        });

        CheckAvailSpaceBtn.setBackground(new java.awt.Color(195, 215, 217));
        CheckAvailSpaceBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CheckAvailSpaceBtn.setText("Check Available Space");
        CheckAvailSpaceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckAvailSpaceBtnActionPerformed(evt);
            }
        });

        ParkBikeBtn.setBackground(new java.awt.Color(195, 215, 217));
        ParkBikeBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ParkBikeBtn.setForeground(new java.awt.Color(0, 0, 0));
        ParkBikeBtn.setText("Park Bike");
        ParkBikeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParkBikeBtnActionPerformed(evt);
            }
        });

        JoinWaitingListBtn.setBackground(new java.awt.Color(195, 215, 217));
        JoinWaitingListBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JoinWaitingListBtn.setText("Join Waiting List");
        JoinWaitingListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JoinWaitingListBtnActionPerformed(evt);
            }
        });

        RemoveBikeBtn.setBackground(new java.awt.Color(195, 215, 217));
        RemoveBikeBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RemoveBikeBtn.setText("Remove Bike");
        RemoveBikeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveBikeBtnActionPerformed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(127, 140, 141));
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CheckAvailSpaceBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JoinWaitingListBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RemoveBikeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ownerNameLbl)
                                            .addComponent(bikeIdLbl))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bikeIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(OwnerNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(ParkBikeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(9, 9, 9))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bikeIdLbl)
                    .addComponent(bikeIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ownerNameLbl)
                    .addComponent(OwnerNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ParkBikeBtn)
                .addGap(18, 18, 18)
                .addComponent(CheckAvailSpaceBtn)
                .addGap(18, 18, 18)
                .addComponent(JoinWaitingListBtn)
                .addGap(18, 18, 18)
                .addComponent(RemoveBikeBtn)
                .addGap(18, 18, 18)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void clearAll(){
        bikeIdTF.setText("");
        OwnerNameTF.setText("");
    }
    private void bikeIdTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bikeIdTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bikeIdTFActionPerformed

    private void OwnerNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OwnerNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OwnerNameTFActionPerformed

    private void CheckAvailSpaceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckAvailSpaceBtnActionPerformed
        int available = maxSpaces - parkedBikes;
        JOptionPane.showMessageDialog(null,
                "Available parking spaces: " + available);
    }//GEN-LAST:event_CheckAvailSpaceBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void ParkBikeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParkBikeBtnActionPerformed
    if(bikeIdTF.getText().isEmpty() || OwnerNameTF.getText().isEmpty()){
        JOptionPane.showMessageDialog(null,"Enter Bike ID and Owner Name");
        return;
    }
    
    Bike bike = new Bike();
    bike.setBikeId(bikeIdTF.getText());
    bike.setOwnerName(OwnerNameTF.getText());

    if (parkedBikes < maxSpaces) {
        parkingStack.push(bike);
        parkedBikes++;
        JOptionPane.showMessageDialog(null,"Bike parked successfully");
    } 
    else {
        JOptionPane.showMessageDialog(null,"Parking full. Please join the waiting list");
    }
    
    clearAll();
    }//GEN-LAST:event_ParkBikeBtnActionPerformed

    private void JoinWaitingListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JoinWaitingListBtnActionPerformed
       Bike bike = new Bike();
       bike.setBikeId(bikeIdTF.getText());
       bike.setOwnerName(OwnerNameTF.getText());

       waitingList.add(bike, waitingList.size());

       JOptionPane.showMessageDialog(null,"Bike added to waiting list");
       clearAll();
    }//GEN-LAST:event_JoinWaitingListBtnActionPerformed

    private void RemoveBikeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveBikeBtnActionPerformed
       Bike removedBike = parkingStack.pop();
        if (removedBike == null) {
            JOptionPane.showMessageDialog(null,"No bikes in parking");
        } 
        else {
            parkedBikes--;
            JOptionPane.showMessageDialog(null,"Bike removed: " + removedBike);

            // Assign space to waiting list
            if (!waitingList.isEmpty()) {
                Bike nextBike = (Bike) waitingList.get(0);
                waitingList.remove(nextBike);
                parkingStack.push(nextBike);
                parkedBikes++;
                JOptionPane.showMessageDialog(null,"Bike from waiting list parked: " + nextBike);
             }
          }
    }//GEN-LAST:event_RemoveBikeBtnActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckAvailSpaceBtn;
    private javax.swing.JButton JoinWaitingListBtn;
    private javax.swing.JTextField OwnerNameTF;
    private javax.swing.JButton ParkBikeBtn;
    private javax.swing.JButton RemoveBikeBtn;
    private javax.swing.JLabel bikeIdLbl;
    private javax.swing.JTextField bikeIdTF;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel ownerNameLbl;
    // End of variables declaration//GEN-END:variables
}
